---
filename: s3_config.yaml
signatures:

  - name: S3 Configuration Files
    status: enabled
    author: PaperMtn
    date: "2021-09-24"
    description: Detects exposed S3 configuration files
    severity: "70"
    notes:
    references:
    watchman_apps:
      slack_std:
        scope:
          - files
        file_types:
        search_strings:
          - "s3cfg"
          - "s3cmd.ini"
      slack_eg:
        scope:
          - files
          - drafts
        file_types:
        locations:
          - public
          - private
          - connect
        search_strings:
          - "s3cfg"
          - "s3cmd.ini"
      gitlab:
        scope:
          - blobs
        search_strings:
          - secret extension:s3cfg
          - secret extension:ini
          - s3cmd.ini
    test_cases:
      match_cases:
        - secret_key = 123456789abcdefg123456789123456789
      fail_cases:
        - secret_key = $S3_SECRET_KEY]
    patterns:
      - '(?i)(''|"){0,2}secret_key(''|"){0,2} = (''|"){0,2}([0-9a-zA-Z!@#$&()\/\-`_.+,"]{20,})(''|"){0,2}'

